#!/usr/bin/env bash
# This Script displays information about subdomains.

# Query DNS records & print subdomain info
print_subdomain_info() {
    dig +short "$1" A | awk -v subdomain="$2" 'NR==1 { print "The subdomain " subdomain " is a A record and points to " $1 }'
}

# Check subdomain
# shellcheck disable=SC2086
if [ "$#" -eq 2 ]; then
    print_subdomain_info "$2.$1" "$2"
else
    print_subdomain_info "www.$1" "www"
    print_subdomain_info "lb-01.$1" "lb-01"
    print_subdomain_info "web-01.$1" "web-01"
    print_subdomain_info "web-02.$1" "web-02"
fi
