#!/usr/bin/env bash
# This Script displays information about subdomains.

# Query DNS records
query_dns() {
    sub_domain="$1"
    record_type="$2"
    dig +short "$sub_domain" "$record_type"
}

# Subdomain information
display_info() {
    sub_domain="$1"
    record_type="$2"
    destination=$(query_dns "$sub_domain" "$record_type")
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Entry Point
main() {
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$2" ]; then
        for subdomain in "${subdomains[@]}"; do
            display_info "$subdomain.$domain" A
        done
    else
        display_info "$2.$domain" A
    fi
}

# Call main function
main "$@"
