#!/usr/bin/env bash
# This Script Creates a certificate using certbot & configure HAproxy to accept encrypted traffic

sudo snap install --classic certbot

sudo service haproxy stop

sudo certbot certonly --standalone -d www.hebazaki.tech

sudo mkdir -p /etc/haproxy/certs

DOMAIN='www.hebazaki.tech'
sudo cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem | sudo tee /etc/haproxy/certs/$DOMAIN.pem >/dev/null

sudo chmod -R go-rwx /etc/haproxy/certs

# Step 5: Add SSL Configuration to HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null <<EOF

bind *:443 ssl crt /etc/haproxy/certs/www.hebazaki.tech.pem
redirect scheme https code 301 if !{ ssl_fc }

frontend http_front
    bind *:80
    bind *:443 ssl crt /etc/haproxy/certs/www.hebazaki.tech.pem
    redirect scheme https code 301 if !{ ssl_fc }
    default_backend http_back
EOF

sudo haproxy -f /etc/haproxy/haproxy.cfg -c

sudo openssl dhparam -out /etc/haproxy/dhparams.pem 2048

sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null <<EOF
ssl-dh-param-file /etc/haproxy/dhparams.pem
EOF

sudo service haproxy restart
