#!/usr/bin/env bash
# This script configures a new Ubuntu machine to Install nginx on my server

apt update

apt install -y nginx

service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

service nginx restart
