#!/usr/bin/env bash
# This script configures a new Ubuntu machine to Install nginx on my server

apt update

apt install -y nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

service nginx start
