#!/usr/bin/env bash
# This script configures a new Ubuntu machine to Install nginx on my server

apt update

apt install -y nginx

service nginx start

echo "<html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /usr/share/nginx/html/index.html

service nginx restart
