#!/usr/bin/env bash
# This script configures Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update

sudo apt-get -y install nginx

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
