#!/usr/bin/env bash
# This script configures Nginx server to have a custom 404 page

sudo apt-get -y update

sudo apt-get -y install nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.txt

sudo sed -i '/^}/i \    error_page 404 /404.txt;\n' /etc/nginx/sites-available/default

sudo service nginx restart
