#!/usr/bin/env bash
# This script configures a new Ubuntu machine to Install nginx on my server
# then configure it so that its HTTP response contains a custom header 

sudo apt-get -y update

sudo apt-get -y install nginx

# shellcheck disable=SC2154
SERVER_HOSTNAME=$(hostname -s)

NGINX_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    add_header X-Served-By $SERVER_HOSTNAME;
}"

echo "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-available/default

sudo service nginx start
