#!/usr/bin/env bash
# This script configures a new Ubuntu machine to Install nginx on my server
# then configure it so that its HTTP response contains a custom header 

sudo apt-get -y update

sudo apt-get -y install nginx

# shellcheck disable=SC2154
server_hostname=$(hostname -s)

nginx_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By $server_hostname;

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}"

echo "$nginx_config" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
