#!/usr/bin/env bash
# This script Install and configure HAproxy on lb-01 server.

sudo apt update
sudo apt install -y haproxy

# shellcheck disable=SC2154
server_hostname=$(hostname -s)

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 $server_hostname:80 check
    server web-02 $server_hostname:80 check
EOF

sudo systemctl restart haproxy

sudo systemctl enable haproxy
