#!/usr/bin/env bash
# This script Installs and configures HAproxy on lb-01 server.

sudo apt update
sudo apt install -y haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo mv /etc/haproxy/haproxy.cfg{,.original}

sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen appname
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    stats realm Strictly\ Private
    stats auth A_Username:YourPassword
    stats auth Another_User:passwd
    balance roundrobin
    option httpclose
    option forwardfor
    server 530954-web-01 23.23.73.165:80 check
    server 530954-web-02 54.144.141.225:80 check
EOF

sudo service haproxy restart
