#!/usr/bin/env bash
# This script Installs and configures HAproxy on lb-01 server.

sudo apt update
sudo apt install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 530954-web-01 23.23.73.165:80 check
    server 530954-web-02 54.144.141.225:80 check
EOF

sudo systemctl restart haproxy

sudo systemctl enable haproxy
