#!/usr/bin/env bash
# This script Checks if Nginx is listening on port 80

# Run Check
if ! sudo service nginx status > /dev/null 2>&1; then
    sudo service nginx start
fi

# configuation file
if ! grep -q "listen\s*80;" /etc/nginx/nginx.conf; then
    sudo sed -i '/server {/a listen 80;' /etc/nginx/nginx.conf
    sudo service nginx restart
fi
