#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and exit with SIGTERM.

while true; do
    trap 'echo "I am invincible!!!"; exit' SIGTERM

    echo "To infinity and beyond"
    sleep 2
done
