#!/usr/bin/env bash
# This script is displaying To infinity and beyond indefinitely and exit with SIGTERM.

trap 'echo "I am invincible!!!"; exit' SIGTERM SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
