#!/usr/bin/env bash
# This script is displaying content of a file

file="/etc/passwd"

while IFS=: read -r username _ uid gid gecos home shell; do
    IFS=',' read -r _ _ _ info <<< "$gecos"
    read -r _ _ _ password <<< "$gecos"
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "$file"
