#!/usr/bin/env bash
# This script is displaying content of a file

file="/etc/passwd"

while IFS=: read -r username _ uid gid gecos home shell; do
    IFS=',' read -r _ _ gecos_info <<< "$gecos"
    IFS=' ' read -r _ _ password <<< "$gecos_info"
    if [[ -z $password ]]; then
        password="x"
    fi

    uid_info=$(getent passwd "$uid" | cut -d ':' -f 5)

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $uid_info"
done < "$file"
