#!/usr/bin/env bash
# This script is displaying content of a file

file="/etc/passwd"

while IFS=: read -r username _ uid gid gecos home shell; do
    IFS=',' read -r _ _ _ info <<< "$gecos"
    read -r _ _ _ password <<< "$gecos"
    echo "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < "$file"
