#!/usr/bin/env bash
# This script is displaying if a file exists

if [ -e "school" ]; then
    echo "school file exists"
        if [ -s "$school" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
else
    echo "school file does not exist"
fi
