#!/usr/bin/env bash
# This script is displaying if a file exists

file="school"
if [ -e "$file" ]; then
    echo "school file exists"
        if [ -s "$file" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
else
    echo "school file does not exist"
fi
