#!/usr/bin/env bash
# This Script runs the whoami command under the user passed as an argument

# Check if an argument is provided
if [ $# -ne 1 ]; then
    exit 1
fi

# runs the whoami command under the user passed as an argument
sudo -u "$1" whoami
