#!/usr/bin/env bash
# This Script makes Nginx runs as the nginx user.

# Change permissions of nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Change user in nginx.conf
sed -i 's/\s*#*\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Replace port 80 with port 8080
sed -i 's/\(listen [::]*:*\)80/\18080/' /etc/nginx/sites-enabled/default

# kill any Apache service running
pkill apache2

# Restart Nginx service
sudo -u nginx service nginx start
