#!/usr/bin/env bash
# This Script makes Nginx runs as the nginx user.

# Change permissions of nginx.conf
# chmod u=rw,go=r /etc/nginx/nginx.conf

# Change user in nginx.conf
# sed -i 's/\s*#*\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Replace port 80 with port 8080
# sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Nginx service
# sudo -u nginx service nginx start

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
