#!/usr/bin/env bash
# This Script makes Nginx runs as the nginx user.

chmod u=rw,go=r /etc/nginx/nginx.conf
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
