#!/usr/bin/env bash
# This Script makes Nginx runs as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i 's/\s*#*\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
